api = "0.2"

[buildpack]
  id = "paketo-community/mri"
  name = "MRI Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    mri = "2.7.*"

  [[metadata.dependencies]]
    id = "mri"
    name = "MRI"
    sha256 = "01b7d7a8a3031f15079e0ca1245e002575f47c8943f68508d86ba4f46ac24190"
    source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.7.tar.gz"
    source_sha256 = "0b2d0d5e3451b6ab454f81b1bfca007407c0548dea403f1eba2e429da4add6d4"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.7-linux-x64-cflinuxfs3-01b7d7a8.tgz"
    version = "2.5.7"

  [[metadata.dependencies]]
    id = "mri"
    name = "MRI"
    sha256 = "a23c26ec93e34ca05328390107ff40034b5103afb91194ebf70f66f0c0866db4"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.gz"
    source_sha256 = "66976b716ecc1fd34f9b7c3c2b07bbd37631815377a2e3e85a5b194cfdcbed7d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.6.5-linux-x64-cflinuxfs3-a23c26ec.tgz"
    version = "2.6.5"

  [[metadata.dependencies]]
    id = "mri"
    name = "MRI"
    sha256 = "68cd2baeb33c1f10a873aab8e492d4547f3b13d1a6302930ac25bcedf45d51ce"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.0.tar.gz"
    source_sha256 = "8c99aa93b5e2f1bc8437d1bbbefd27b13e7694025331f77245d0c068ef1f8cbe"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.7.0-linux-x64-cflinuxfs3-68cd2bae.tgz"
    version = "2.7.0"
    
  [[metadata.dependencies]]
    deprecation_date = "2023-04-01T00:00:00Z"
    id = "mri"
    name = "MRI"
    sha256 = "c892f69b474a9669320b11b324f1a3efb4bc7a8a6409f4274aef0056a82a2161"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
    source_sha256 = "d418483bdd0000576c1370571121a6eb24582116db0b7bb2005e90e250eae418"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.7.1_linux_x64_cflinuxfs3_c892f69b.tgz"
    version = "2.7.1"

  [[metadata.dependencies]]
    id = "mri"
    name = "MRI"
    sha256 = "7fe47223bd5815df7317e0c3cf3ff1ad75a259d048d759caa9c6eb4db3bea656"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz"
    source_sha256 = "364b143def360bac1b74eb56ed60b1a0dca6439b00157ae11ff77d5cd2e92291"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.6.6_linux_x64_cflinuxfs3_7fe47223.tgz"
    version = "2.6.6"

  [[metadata.dependencies]]
    id = "mri"
    name = "MRI"
    sha256 = "4749d33a4385cb5cc61dd6e460d474132277fda76cc542e1cdfe45b0df93bdc8"
    source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.8.tar.gz"
    source_sha256 = "6c0bdf07876c69811a9e7dc237c43d40b1cb6369f68e0e17953d7279b524ad9a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.5.8_linux_x64_cflinuxfs3_4749d33a.tgz"
    version = "2.5.8"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-01T00:00:00Z
    link = "https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/"
    name = "mri"
    version_line = "2.7.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
